files:
  - source: /en/gittoolbox/ResourceBundle.properties
    translation: /%two_letters_code%/gittoolbox/ResourceBundle.properties
  - source: /en/intellij/ZResBundle.properties
    translation: /%two_letters_code%/intellij/ZResBundle.properties
