name: Build

on:
  push:
    branches: [ "l10n_main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Build 
        run: |
          sh rebuild.sh
          echo "ZIP_FILE=$(find . -name '*.zip' | xargs basename)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ZIP_FILE }}
          token: ${{ secrets.TOKEN }}
          generateReleaseNotes: true