name: Build

on:
  push:
    branches: [ "l10n_main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4.1.1

      - name: Build 
        run: sh rebuild.sh