name: Build

on:
  push:
    branches: [ "l10n_main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Build 
        run: |
          sh rebuild.sh
          echo "ZIP_FILE=$(find . -name '*.zip' | xargs basename)" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.ZIP_FILE }}
          name: ${{ env.ZIP_FILE }}

      - name: Create GitHub Release
        uses: actions/create-release@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: CI Release
          draft: false
          prerelease: true
