name: Build

on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Update 
        run: |
          sh update.sh

      - name: Commit And Push 
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "feat: Update Version
          git push